#+Title: Syllabus Psych 420 Intro Comp Mod Psychology Students
#+Date: <2021-12-21 Tue>
#+Author: Britt Anderson PhD & MD

* Instructor Information

Instructor: Britt Anderson

Office: PAS 4039 -or- E7 6328

Office Hours: email to arrange virtual office hour

Phone: never checked; just *email*
(alternate contacts include an issue on the course github (not LEARN) site - see below).

Email: britt@uwaterloo.ca

* Course Description

** Brief Description

An introduction to the basic elements of computational modeling with an emphasis on psychology students.

** Goals

   1. You will understand the scope of subject topics and methodological tools that comprise computational neuroscience and computational cognitive modeling
   2. You will learn the skills necessary to program a spiking neuron model, and have a general understanding of the mathematics behind it (differential equations).
   3. You will learn the skills necessary to code a simple neural network, and have a general understanding of the mathematics behind it (linear algebra).
   4. We may, given time, cover an additional topic or two, but we will always conclude with the goal of you...
   5. Using your burgeoning skills to collaborate in a group to program a simple model of something neurological or psychological and provide supporting background material as to why this project is apt for a modeling approach.

** Text
This is no required text for this course, but much of the material was covered to some extent in my book that you can find online through the library:

[[
https://ocul-wtl.primo.exlibrisgroup.com/discovery/fulldisplay?docid=alma9951382083505162&context=L&vid=01OCUL_WTL:WTL_DEFAULT&lang=en&search_scope=OCULDiscoveryNetwork&adaptor=Local%20Search%20Engine&tab=OCULDiscoveryNetwork&query=any,contains,britt%20anderson&offset=0][Computational neuroscience and cognitive modelling a student's introduction to methods and procedures]]

Most of material that students need can be found in the course github repository: [[https://github.com/brittAnderson/compNeuroIntro420/][Comp-Neuro-420]]. Make sure you track the "lisp" branch.

** Requirements and Assessments

   *Special Requirements*

Because we are, at least in the beginning, in a virtual setting it will be imperative that attend all classes, and participate in the in-class activities.

This will require having a functioning:

- laptop on which they can install software
- using the zoom application to be able to view multiple screens and share their own screen
- a reliable internet connection with a camera, sound, and microphone that will be left on by default.

** Graded Assignments
These will take two forms: regular exercises and a final project.

***  Regular Exercises.
These are short in-class presentations on particular topics that will be assigned in real time. There will also be homework exercises to be done in the time between course sessions. These will be turned in a dropbox on Learn. We will generally only use Learn for this sort of administrative function. I will expand this list, but for now, and given the uncertainty of our meeting conditions it will remain partial.

*** Final project

*** Extra Credit:
**** Sona Participation and Research Experience Marks
- Information and Guidelines
  Experiential learning is considered an integral part of the undergraduate program in Psychology. Research participation is one example of this, article review is another. A number of undergraduate courses have been expanded to include opportunities for Psychology students to earn grades while gaining research experience.

Since experiential learning is highly valued in the Department of Psychology, students may earn a "bonus" grade of up to 3% in this course through research experience. Course work will make up 100% of the final mark and a "bonus" of up to 3% may be earned and will be added to the final grade if/as needed to bring your final grade up to 100%.

The two options for earning research experience grades; participation in research through online and remotely operated (replacing in-lab) studies, and article review; are described below. Students may complete any combination of these options to earn research experience grades. 
Option 1: Participation in Psychology Research

Research participation is coordinated by the Research Experiences Group (REG). Psychology students may volunteer as research participants in remotely operated (replaces in-lab) and/or online (web-based) studies conducted by students and faculty in the Department of Psychology. Participation enables students to learn first-hand about psychology research and related concepts. Many students report that participation in research is both an educational and interesting experience. Please be assured that all Psychology studies have been reviewed and received ethics clearance through a University of Waterloo Research Ethics Committee. 

How to earn extra marks for your Psychology course(s) this term by participating in studies ...
-  You will earn "credits" which will be converted to "marks" (1 credit = 1%)
-  You can schedule your remotely operated (replacing in-lab) and ONLINE studies using the "Sona" website.
-  FOR THE WINTER 2022 TERM ALL OF YOUR CREDITS can be earned through ONLINE AND REMOTELY/ ONLINE OPERATED (replacing in-lab) studies. This could change as advice on in lab studies progresses.
- tional focus of participation in research
- ximize the educational benefits of participating in research, students will receive feedback information following their participation in each study detailing the following elements:
-  Purpose or objectives of the study
-  Dependent and independent variables
-  Expected results 
-  References for at least two related research articles
-  Provisions to ensure confidentiality of data
-  Contact information of the researcher should the student have further questions about the study
-  Contact information for the Director of the Office of Research Ethics should the student wish to learn more about the general ethical issues surrounding research with human participants, or specific questions or concerns about the study in which s/he participated. 

Participation in remotely operated (replaces in-lab) studies has increment values of 0.75 participation credits (grade percentage points) for each 30-minutes of participation. Participation in ONLINE studies is worth .25 credits for each 15-minutes of participation.  Researchers will record student’s participation and at the end of the term the REG Coordinator will provide the course instructor with a credit report of the total credits earned by each student.  

How to participate?

Study scheduling, participation and grade assignment is managed using the SONA online system.  All students enrolled in this course have been set up with a SONA account.  You must get started early in the term.

For instructions on how to log in to your SONA account and for a list of important dates and deadlines please, as soon as possible, go to:
Participating/SONA information:  How to log in to Sona and sign up for studies

/Please do not ask the Course Instructor or REG Coordinator for information unless you have first thoroughly read the information provided on this website./

More information about the REG program in general is available at: 

Sona Information on the REG Participants website or you can check the Sona FAQ on the REG website homepage for additional information. 

Option 2: Article Review as an alternative to participation in research
Students are not required to participate in research, and not all students wish to do so. As an alternative, students may opt to gain research experience by writing short reviews (1½ to 2 pages) of research articles relevant to the course. The course instructor will specify a suitable source of articles for this course (i.e., scientific journals, newspapers, magazines, other printed media). You must contact your TA to get approval for the article you have chosen before writing the review. Each review article counts as one percentage point. To receive credit, you must follow specific guidelines.

The article review must:

- Be submitted before the last day of lectures. Late submissions will NOT be accepted under ANY circumstances.
- Be typed
- Fully identify the title, author(s), source and date of the article. A copy of the article must be attached.
- Identify the psychological concepts in the article and indicate the pages in the textbook that are applicable. Critically evaluate the application or treatment of those concepts in the article. If inappropriate or incorrect, identify the error and its implications for the validity of the article. You may find, for example, misleading headings, faulty research procedures, alternative explanations that are ignored, failures to distinguish factual findings from opinions, faulty statements of cause-effect relations, errors in reasoning, etc. Provide examples whenever possible. 
- Clearly evaluate the application or treatment of those concepts in the article.
- Keep a copy of your review in the unlikely event we misplace the original.




IAMHERE
