#+OPTIONS: ':nil *:t -:t ::t <:t H:3 \n:nil ^:t arch:headline
#+OPTIONS: author:t c:nil creator:nil d:(not "LOGBOOK") date:t e:t
#+OPTIONS: email:nil f:t inline:t num:t p:nil pri:nil prop:nil stat:t
#+OPTIONS: tags:t tasks:t tex:t timestamp:t title:t toc:t todo:t |:t
#+TITLE: tools
#+DATE: <2016-11-09 Wed>
#+AUTHOR: Britt Anderson
#+EMAIL: britt@uwaterloo.ca
#+LANGUAGE: en
#+SELECT_TAGS: export
#+EXCLUDE_TAGS: noexport
#+CREATOR: Emacs 25.1.1 (Org mode 8.3.6)
* Operating Systems
** Windows
** MacOS
** Linux Flavors
*** Debian
*** Buntus
    1. Ubuntu
    2. Xubuntu
    3. Lubuntu
*** Archlinux
** BSDs
*** OpenBSD
*** FreeBSD
*** NetBSD

* Terminals

First there was the command line

* IDEs
  What is an IDE?

** Emacs
   Why:
   
   Basics:
   
*** For Windows
    https://www.gnu.org/software/emacs/manual/efaq-w32.html

    
*** For Mac
    try homebrew
   
   
*** For Linux
    use your package manager

** Vim

  
** Atom 
   https://github.com/atom/atom

* Help
** Stackoverflow

* Version Control
** Git
   For windows and mac users can try this: https://desktop.github.com/

   Here is another option: https://git-for-windows.github.io/

   Linux people can just install "git" as a package

   For Mac can also consider using [[http://brew.sh/][Homebrew]]
** Mercury

** Others
  
*** CVS

*** SVN

*** Darcs

* Programming Languages
** R 
*** Base R
    https://cran.r-project.org/
*** Rstudio 
    R with an ide
    https://www.rstudio.com/
** Python2
   
   A windows guide: http://docs.python-guide.org/en/latest/starting/install/win/

   On mac you probably already have it

   Same with Linux. If not, get it from your package manager. 

*** Learn the basics 

    https://opencs.uwaterloo.ca/

*** Literate Programming with Python - Project Jupyter (IPython)
    
    - Jupyter [[http://jupyter.org][website]]
    
** Haskell

   Not for the faint of heart on any other OS but Linux

   Two options. Many people now prefer STACK for ease of use. https://docs.haskellstack.org/en/stable/install_and_upgrade/

   But old school types use their package manager or, if on Windows try 

** Lisp

   Some of you may have heard about this as the language of GOFAI (good old fashioned AI). This can be a bear, but you have a version of lisp if you grabbed emacs. Emacs is written in a dialect of lisp called Elisp, and it can give you a flavor of using the language. 
** Octave/Matlab
   - Matlab
     - [[https://www.mathworks.com/products/matlab.html][Corporate Site]]
     - Available on Nexus Machines (see [[https://uwaterloo.ca/information-systems-technology/services/scientific-computing-software-support/supported-software-scientific-computing/matlab][MATLAB for coursework]]).
   - Octave 
     Open source alternative. Similar, but not identical.
     - [[https://www.gnu.org/software/octave/][Main site]]
     - [[https://youtu.be/npz2pBIc9CU][Youtube Demo for EEG Analysis]]
     
