* Technical Details
** Zoom

  Invitation:

Topic: Psych 420/792
Time: Jan 6, 2022 02:30 PM Eastern Time (US and Canada)
        Every week on Thu, 13 occurrence(s)
        Jan 6, 2022 02:30 PM
        Jan 13, 2022 02:30 PM
        Jan 20, 2022 02:30 PM
        Jan 27, 2022 02:30 PM
        Feb 3, 2022 02:30 PM
        Feb 10, 2022 02:30 PM
        Feb 17, 2022 02:30 PM
        Feb 24, 2022 02:30 PM
        Mar 3, 2022 02:30 PM
        Mar 10, 2022 02:30 PM
        Mar 17, 2022 02:30 PM
        Mar 24, 2022 02:30 PM
        Mar 31, 2022 02:30 PM

Join Zoom Meeting
https://uwaterloo.zoom.us/j/91091259763?pwd=dmh4aEhGbWJpOVlrNGdheEFuSWxGdz09

[[file:zoom-codes.txt][zoom codes]]

* Computer
  You will need a computer.

  You need to be able to install software on it.

  You need to have a reliable internet communication (camera, speaker, mic). *Recommended* use a wired connection for your internet connection *not* wifi.

  You should provide yourself a working installation of either R or Python. If you know both of the languges well and want to use a different one for the class exercises that is probably fine just, but  get my permission for that language in advance.

* Facebook
  General comments.

  
* Talk to me
  - letters of recommendation
  - quality of your education
