cabal-version:      3.0
name:               w2026
version:            0.1.0.0
-- synopsis:
-- description:
license:            BSD-3-Clause
license-file:       LICENSE
author:             Britt Anderson
maintainer:         britt@uwaterloo.ca
-- copyright:
category:           education
build-type:         Simple
extra-doc-files:    CHANGELOG.md
-- extra-source-files:

common warnings
    ghc-options: -Wall

library
    import:           warnings
    exposed-modules:  Dev
                    , MyLib
                    , BusyBeaver
                    , IandF
                    , HandH
                    , Spring 
                    , Sqrt
                    , Automata
                    , MyMats
                    , Perceptron
                    , Hopfield
    -- other-modules: 
    -- other-extensions:
    build-depends:    base ^>=4.18.3.0
                    , gnuplot ^>=0.5.6
                    , containers ^>=0.6.7
                    , JuicyPixels ^>=3.3.9
                    , array
                    , random
    hs-source-dirs:      src
    default-language: Haskell2010
    
test-suite w2026-test
    import:           warnings
    type:             exitcode-stdio-1.0
    main-is:          Spec.hs
    hs-source-dirs:   test
    build-depends:    base ^>=4.18.3.0
                    , w2026
                    , hspec ^>=2.11.10
                    , QuickCheck
    default-language: Haskell2010
    build-tool-depends: hspec-discover:hspec-discover
    ghc-options:      -threaded -rtsopts -with-rtsopts=-N

