cabal-version:      3.0
name:               w2026
version:            0.1.0.0
-- synopsis:
-- description:
license:            BSD-3-Clause
license-file:       LICENSE
author:             Britt Anderson
maintainer:         britt@uwaterloo.ca
-- copyright:
category:           education
build-type:         Simple
extra-doc-files:    CHANGELOG.md
-- extra-source-files:

common warnings
    ghc-options: -Wall

library
    import:           warnings
    exposed-modules:  MyLib
    -- other-modules:
    -- other-extensions:
    build-depends:    base ^>=4.18.3.0
                    , gnuplot ^>=0.5.6
    hs-source-dirs:   src
    default-language: Haskell2010
